-- Initial PostgreSQL schema for Kinaadman.
-- Runtime backend uses PostgreSQL via DATABASE_URL.

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  fullname VARCHAR(100) NOT NULL,
  role text NOT NULL DEFAULT 'user',
  reset_token VARCHAR(255) NULL,
  reset_token_expiry bigint NULL,
  approval_status text NOT NULL DEFAULT 'approved',
  approved_by integer NULL,
  approved_at timestamp NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active boolean NOT NULL DEFAULT false,
  CONSTRAINT fk_users_approved_by FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE SET NULL
) ;

CREATE TABLE IF NOT EXISTS transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  docno VARCHAR(20) NOT NULL UNIQUE,
  type text NOT NULL,
  client VARCHAR(255) NOT NULL,
  address TEXT,
  tin VARCHAR(20),
  bizstyle VARCHAR(100),
  phone VARCHAR(20),
  description TEXT,
  archived boolean DEFAULT false,
  archived_auto boolean NOT NULL DEFAULT false,
  qty integer NOT NULL DEFAULT 1,
  unitprice DECIMAL(12,2),
  amount DECIMAL(12,2) NOT NULL,
  downpayment DECIMAL(12,2) NOT NULL DEFAULT 0,
  checkno VARCHAR(100),
  pono VARCHAR(100),
  date DATE NOT NULL,
  status text NOT NULL DEFAULT 'unpaid',
  pdfFilename VARCHAR(255),
  project_members VARCHAR(255),
  member_role VARCHAR(50),
  member_phone VARCHAR(20),
  project_members_2 VARCHAR(255),
  member_role_2 VARCHAR(50),
  member_phone_2 VARCHAR(20),
  project_members_3 VARCHAR(255),
  member_role_3 VARCHAR(50),
  member_phone_3 VARCHAR(20),
  project_start_date DATE,
  project_end_date DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ;

CREATE TABLE IF NOT EXISTS vendors (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_name VARCHAR(255) NOT NULL,
  contact_person VARCHAR(100),
  email VARCHAR(100),
  phone VARCHAR(20),
  address TEXT,
  tin VARCHAR(20),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ;

CREATE TABLE IF NOT EXISTS projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name VARCHAR(255) NOT NULL,
  transaction_id integer NULL,
  source_docno VARCHAR(20),
  description TEXT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  planned_start_date DATE DEFAULT NULL,
  planned_end_date DATE DEFAULT NULL,
  actual_start_date DATE DEFAULT NULL,
  actual_end_date DATE DEFAULT NULL,
  status_reason TEXT,
  paused_at DATE DEFAULT NULL,
  cancelled_at DATE DEFAULT NULL,
  project_manager VARCHAR(100),
  status text DEFAULT 'planning',
  priority text DEFAULT 'medium',
  is_archived boolean NOT NULL DEFAULT false,
  archived_auto boolean NOT NULL DEFAULT false,
  budget DECIMAL(15,2) NOT NULL,
  members VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_projects_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id)
) ;

CREATE TABLE IF NOT EXISTS purchase_orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_number VARCHAR(50) NOT NULL UNIQUE,
  vendor_id integer NOT NULL,
  po_date DATE NOT NULL,
  delivery_date DATE,
  payment_terms VARCHAR(100),
  prepared_by VARCHAR(255),
  approved_by VARCHAR(255),
  total_amount DECIMAL(12,2) NOT NULL,
  status text DEFAULT 'draft',
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_orders_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id)
) ;

CREATE TABLE IF NOT EXISTS po_line_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id integer NOT NULL,
  description TEXT,
  quantity integer NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  line_total DECIMAL(12,2) NOT NULL,
  received_qty integer DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_po_line_items_po FOREIGN KEY (po_id) REFERENCES purchase_orders (id)
) ;

CREATE TABLE IF NOT EXISTS accounts_payable (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id integer NOT NULL,
  bill_number VARCHAR(50) NOT NULL UNIQUE,
  invoice_number VARCHAR(50),
  bill_date DATE NOT NULL,
  due_date DATE,
  po_id integer NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  paid_amount DECIMAL(12,2) DEFAULT 0,
  status text DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_accounts_payable_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id),
  CONSTRAINT fk_accounts_payable_po FOREIGN KEY (po_id) REFERENCES purchase_orders (id)
) ;

CREATE TABLE IF NOT EXISTS accounts_receivable (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  invoice_number VARCHAR(50) NOT NULL UNIQUE,
  invoice_date DATE NOT NULL,
  due_date DATE,
  total_amount DECIMAL(12,2) NOT NULL,
  paid_amount DECIMAL(12,2) DEFAULT 0,
  status text DEFAULT 'draft',
  transaction_id integer NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_accounts_receivable_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id)
) ;

CREATE TABLE IF NOT EXISTS payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_type text NOT NULL,
  ap_id integer NULL,
  ar_id integer NULL,
  payment_date DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  payment_method text DEFAULT 'cash',
  reference_number VARCHAR(100),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_ap FOREIGN KEY (ap_id) REFERENCES accounts_payable (id),
  CONSTRAINT fk_payments_ar FOREIGN KEY (ar_id) REFERENCES accounts_receivable (id)
) ;

CREATE TABLE IF NOT EXISTS system_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NULL,
  action VARCHAR(100) NOT NULL,
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_system_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ;

CREATE TABLE IF NOT EXISTS tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL,
  task_name VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  duration integer,
  progress integer DEFAULT 0,
  assigned_to VARCHAR(100),
  status text DEFAULT 'not_started',
  plan_cost DECIMAL(12,2) DEFAULT 0,
  actual_cost DECIMAL(12,2) DEFAULT 0,
  dependencies integer,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects (id)
) ;

CREATE TABLE IF NOT EXISTS project_costs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL,
  task_id integer NULL,
  cost_category VARCHAR(100),
  plan_amount DECIMAL(12,2) NOT NULL,
  actual_amount DECIMAL(12,2) DEFAULT 0,
  variance DECIMAL(12,2),
  cost_date DATE,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_project_costs_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_project_costs_task FOREIGN KEY (task_id) REFERENCES tasks (id)
) ;

CREATE TABLE IF NOT EXISTS project_resources (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL,
  task_id integer NULL,
  resource_name VARCHAR(100) NOT NULL,
  resource_type text DEFAULT 'labor',
  quantity DECIMAL(10,2),
  unit_cost DECIMAL(12,2),
  allocation integer DEFAULT 100,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_project_resources_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_project_resources_task FOREIGN KEY (task_id) REFERENCES tasks (id)
) ;
