CREATE TABLE IF NOT EXISTS service_orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  so_number varchar(50) NOT NULL UNIQUE,
  business_entity_id integer NULL,
  vendor_id integer NULL,
  company_id integer NOT NULL,
  project_id integer NULL,
  service_type varchar(100) NOT NULL DEFAULT 'installation',
  service_date date NOT NULL,
  service_title varchar(255) NOT NULL,
  description text NULL,
  total_amount decimal(15,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'issued',
  notes text NULL,
  pdfFilename varchar(255) NULL,
  is_archived boolean NOT NULL DEFAULT false,
  archived_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS company_id integer NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS project_id integer NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS service_order_id integer NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS project_tx_no integer NULL;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS company_id integer NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS company_no varchar(20) NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS company_name varchar(255) NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_name varchar(255) NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_docno varchar(20) NULL;

ALTER TABLE accounts_receivable ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE accounts_receivable ADD COLUMN IF NOT EXISTS project_id integer NULL;

ALTER TABLE accounts_payable ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE accounts_payable ADD COLUMN IF NOT EXISTS project_id integer NULL;

ALTER TABLE purchase_requisitions ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE purchase_requisitions ADD COLUMN IF NOT EXISTS company_id integer NULL;
ALTER TABLE purchase_requisitions ADD COLUMN IF NOT EXISTS project_id integer NULL;
ALTER TABLE purchase_requisitions ADD COLUMN IF NOT EXISTS requested_by_email varchar(255) NULL;
ALTER TABLE purchase_requisitions ADD COLUMN IF NOT EXISTS pdfFilename varchar(255) NULL;

ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS company_id integer NULL;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS project_id integer NULL;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS requisition_id integer NULL;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS business_entity_id integer NULL;
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS company_id integer NULL;
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS vendor_no varchar(20) NULL;

CREATE INDEX IF NOT EXISTS idx_service_orders_company_id ON service_orders (company_id);
CREATE INDEX IF NOT EXISTS idx_service_orders_project_id ON service_orders (project_id);
CREATE INDEX IF NOT EXISTS idx_service_orders_service_date ON service_orders (service_date);
CREATE INDEX IF NOT EXISTS idx_service_orders_status ON service_orders (status);
CREATE INDEX IF NOT EXISTS idx_service_orders_vendor_id ON service_orders (vendor_id);
